[package]
name = "cargo-depgraph"
version = "0.1.0"
authors = ["Jonas Platte <jplatte@posteo.de>"]
license = "GPL-3.0-or-later"
edition = "2018"

[dependencies]
anyhow = "1.0.31"
cargo_metadata = "0.10.0"
clap = "2.33.1"
petgraph = { version = "0.5.1", default-features = false, features = ["stable_graph"] }
semver = "0.9.0" # version needs to be the one cargo_metadata uses
